#!/bin/bash

# make release for compiled structure to public Github repo

workingDirectory=$(pwd)

destinationFolder=$1
build=$2
version=$3

mkdir $HOME/Documents/another_repo/

# $WHO_TO_TRUST is secret in environment variable set in main.yml jobs section as first thing before everything

git clone https://madamov:$WHO_TO_TRUST@github.com/clearviewsys/cxr_update_cs.git $HOME/Documents/another_repo

rm -R $HOME/Documents/another_repo/*

# mkdir $HOME/Documents/another_repo/${build}/


echo "🐚 🐚 : Making release of compiled structure ..."
cd $destinationFolder
cd Compiled\ Database
cd CXR7

# make Settings folder for directory.json file
mkdir Settings
cp $workingDirectory/buildFiles/directory.json Settings/directory.json
cp -R $workingDirectory/Flags_Exported Flags_Exported
cp -R $workingDirectory/WebFolder WebFolder
cp -R $workingDirectory/WebDocuments WebDocuments


echo "🐚 🐚 : Copying files ..."

# cp -R * $HOME/Documents/another_repo/${build}/
cp -R * $HOME/Documents/another_repo/


# ls -al $HOME/Documents/another_repo/${build}/ > $HOME/Documents/artifacts/build_listing.txt
ls -alR $HOME/Documents/another_repo/ > $HOME/Documents/artifacts/build_listing.txt

echo "🐚 🐚 : End copying to release repository ..."
