name: My artifacts test

on:

  workflow_dispatch:
     branches: 
       - main

jobs:
    build-on-mac:
       runs-on: macos-latest
       steps:
          - uses: actions/checkout@v4
          - name: 'Kreiraj folder i fajlove u njemu'
            env:
                BINARIES_USER: ${{secrets.BINARIES_USER}}
                BINARIES_PASSWORD: ${{secrets.BINARIES_PASSWORD}}
            run: |
              myfolder=1010
              mkdir $HOME/Documents/$myfolder
              mkdir $HOME/Documents/$myfolder/artifacts
              ls -al $HOME > $HOME/Documents/$myfolder/artifacts/listing.txt
              echo "artifacts_path=$HOME/Documents/$myfolder/artifacts" >> $GITHUB_ENV

          - uses: actions/upload-artifact@v4
            with:
              name: 'Uploading macOS artifacts'
              path: ${{ env.artifacts_path }}  
