name: Test SFTP credentials

on:

  workflow_dispatch:
     branches: 
       - main
       - develop
       - test

jobs:
   test-on-mac:
      runs-on: macos-lastest
      env:
         BINARIES_USER: ${{secrets.BINARIES_USER}
         BINARIES_PASSWORD: ${{secrets.BINARIES_PASSWORD}}}
         UPLOAD_USER: ${{ secrets.UPLOAD_USER }}
         UPLOAD_PASSWORD: ${{ secrets.UPLOAD_PASSWORD }}
         UPLOAD_TEST_USER: ${{ secrets.UPLOAD_USER }}
         UPLOAD_TEST_PASSWORD: ${{ secrets.UPLOAD_PASSWORD }}
         
      steps:
         - name: Testing download and upload
         
         run: |

            licurl=$(jq -r '.maclicenses_URL' $GITHUB_WORKSPACE/buildFiles/parameters.json)
         
            myurl=$(echo $licurl | sed 's/https:\/\//&'"$BINARIES_USER:$BINARIES_PASSWORD@/")

            echo $myurl
         
            curl -s -f -o $HOME/Documents/dev_lic.zip $myurl

            uploadURL=$(jq -r '.uploadCompiledStruct' $GITHUB_WORKSPACE/buildFiles/parameters.json)
 
            echo $uploadURL
         
            echo "Uploading to release SFTP"
         
            curl -k -u ${UPLOAD_USER}:${UPLOAD_PASSWORD} -T $HOME/Documents/dev_lic.zip ${uploadURL}/dev_lic_1.zip

            echo "Uploading to test SFTP"

            uploadTestURL=$(jq -r '.uploadCompiledStruct' $GITHUB_WORKSPACE/buildFiles/parameters_testserver.json)

            echo $uploadTestURL

            curl -k -u ${UPLOAD_TEST_USER}:${UPLOAD_TEST_PASSWORD} -T $HOME/Documents/dev_lic.zip ${uploadTestURL}/dev_lic_2.zip
