name: My artifacts test

on:

  workflow_dispatch:
     branches: 
       - main
       - MA/testing-checking-branch
jobs:
    build-on-mac:
       runs-on: macos-latest
       steps:
          - uses: actions/checkout@v4
          - name: 'Kreiraj folder i fajlove u njemu'
            env:
                BINARIES_USER: ${{secrets.BINARIES_USER}}
                BINARIES_PASSWORD: ${{secrets.BINARIES_PASSWORD}}
                
            run: |

              workingDirectory=$(pwd)

              ls -al $workingDirectory/buildFiles/
              
              if [[ ${{ github.ref == 'refs/heads/MA/testing-checking-branch' }} ]]; then
                 echo in checking branch
                 mv $workingDirectory/buildFiles/parameters_testserver.json $workingDirectory/buildFiles/parameters.json
              fi
              
              myfolder=$(jq -r '.build' $workingDirectory/buildFiles/parameters.json)
              mkdir $HOME/Documents/$myfolder
              mkdir $HOME/Documents/$myfolder/artifacts
              ls -al $HOME > $HOME/Documents/$myfolder/artifacts/listing.txt
              echo "artifacts_path=$HOME/Documents/$myfolder/artifacts" >> $GITHUB_ENV   
              win4d=$(jq -r '.win4D_URL' $workingDirectory/buildFiles/parameters.json)
              winvl=$(jq -r '.winVL_URL' $workingDirectory/buildFiles/parameters.json)
              echo 4D binary is $win4d
              echo volume desktop binary is $winvl


          - uses: actions/upload-artifact@v4
            with:
              name: 'Uploading macOS artifacts'
              path: ${{ env.artifacts_path }}  

    build-on-windows:
       runs-on: windows-latest
       steps:
          - uses: actions/checkout@v4
          - id: step1
            name: 'Kreiraj folder i fajlove u njemu'
            env:
                BINARIES_USER: ${{secrets.BINARIES_USER}}
                BINARIES_PASSWORD: ${{secrets.BINARIES_PASSWORD}}
                MYBRANCH: ${{github.ref}}
                
            run: |

                echo I am in branch %MYBRANCH% 
                if [%MYBRANCH%] == [refs/heads/MA/testing-checking-branch] (move /y buildFiles\parameters_testserver.json  buildFiles\parameters.json)

                mkdir %HOMEDRIVE%%HOMEPATH%\Documents\artifacts
                dir /s *.* > %HOMEDRIVE%%HOMEPATH%\Documents\artifacts\dirlisting_uploadbat.txt
            shell: cmd

          - id: step2
            name: 'Set artifacts path env variable'
            
            run: |
               mkdir testing
               echo "This is a file to upload" > testing/file.txt
               echo "artifactPath=testing/file.txt" >> $GITHUB_ENV   


    build-on-ubuntu:
       runs-on: ubuntu-latest
       steps:    
          - name: Branch-based environment variables that rock
            uses: iamtheyammer/branch-env-vars@v1.2.1
            with:
              UPLOAD_USER: |
                main: ${{secrets.UPLOAD_USER}}
                MA/testing-checking-branch: ${{secrets.UPLOAD_TEST_USER}}

              UPLOAD_PASSWORD: |
                main: ${{secrets.UPLOAD_PASSWORD}}
                MA/testing-checking-branch: ${{secrets.UPLOAD_TEST_PASSWORD}}

              TESTME: |
                main: I am in main
                MA/testing-checking-branch: MA BRANCH IS THIS
                                
          - uses: actions/checkout@v4
          - id: stepinubuntu
            name: 'Testing CURL and other things'
            env:
               UPLOAD_USER: ${{secrets.UPLOAD_USER}}
               UPLOAD_PASSWORD: ${{secrets.UPLOAD_PASSWORD}} 
                   
            run: |
               
               echo $TESTME
               
               workingDirectory=$(pwd)
               ls -al $workingDirectory/buildFiles/
               if [[ ${{ github.ref == 'refs/heads/MA/testing-checking-branch' }} ]]; then
                 echo in checking branch
                 mv $workingDirectory/buildFiles/parameters_testserver.json $workingDirectory/buildFiles/parameters.json
               fi
              
               myfolder=$(jq -r '.build' $workingDirectory/buildFiles/parameters.json)
               uploadurl=$(jq -r '.uploadMacStandalone' $workingDirectory/buildFiles/parameters.json)

               echo $myfolder
               echo $HOME
               echo $uploadurl
               
               mkdir $HOME/$myfolder
               mkdir $HOME/$myfolder/artifacts
               ls -Ral $workingDirectory/buildFiles/ > $HOME/$myfolder/artifacts/listing.txt
               ls -al $HOME/$myfolder/artifacts/
               echo "artifacts_path=$HOME/$myfolder/artifacts" >> $GITHUB_ENV   
               win4d=$(jq -r '.win4D_URL' $workingDirectory/buildFiles/parameters.json)
               winvl=$(jq -r '.winVL_URL' $workingDirectory/buildFiles/parameters.json)
               echo 4D binary is $win4d
               echo volume desktop binary is $winvl
               
               curl -k -u ${UPLOAD_USER}:${UPLOAD_PASSWORD} --ftp-create-dirs -T $HOME/$myfolder/artifacts/listing.txt $uploadurl/listing.txt 

          - uses: actions/upload-artifact@v4
            with:
              name: 'Uploading Ubuntu artifacts'
              path: ${{ env.artifacts_path }}          
